// flow-typed signature: 0629028adf5a1e98ba9bb57e6b7d5bea
// flow-typed version: <<STUB>>/@types/css_v^0.0.30/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/css' {
  declare module.exports: any;
}
