// flow-typed signature: 8ce76c32af09d73315e5aee0aa62a677
// flow-typed version: <<STUB>>/@types/css_v^0.0.30/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/css' {
  declare module.exports: any;
}
