// flow-typed signature: 75d82cea00ec7b2a45a0fc4268afc6a2
// flow-typed version: <<STUB>>/@types/css_v^0.0.30/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/css' {
  declare module.exports: any;
}
