// flow-typed signature: 56e7ad2f6ebe7a7cc410d480fdc9cb43
// flow-typed version: <<STUB>>/@types/isomorphic-fetch_v^0.0.31/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/isomorphic-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/isomorphic-fetch' {
  declare module.exports: any;
}
