// flow-typed signature: 9a1918f845640cbf050c27e344d574d2
// flow-typed version: <<STUB>>/@types/react-modal_v^1.6.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-modal' {
  declare module.exports: any;
}
