// flow-typed signature: 811b3b6e23e874daa78697674b935079
// flow-typed version: <<STUB>>/@types/react-modal_v^1.3.6/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-modal' {
  declare module.exports: any;
}
