// flow-typed signature: c0019bf58c0abffd005dcd618a1559b7
// flow-typed version: <<STUB>>/counterpart_v^0.17.6/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'counterpart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'counterpart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'counterpart/locales/de' {
  declare module.exports: any;
}

declare module 'counterpart/locales/en' {
  declare module.exports: any;
}

declare module 'counterpart/locales/pt-br' {
  declare module.exports: any;
}

declare module 'counterpart/locales/ru' {
  declare module.exports: any;
}

declare module 'counterpart/strftime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'counterpart/index' {
  declare module.exports: $Exports<'counterpart'>;
}
declare module 'counterpart/index.js' {
  declare module.exports: $Exports<'counterpart'>;
}
declare module 'counterpart/locales/de.js' {
  declare module.exports: $Exports<'counterpart/locales/de'>;
}
declare module 'counterpart/locales/en.js' {
  declare module.exports: $Exports<'counterpart/locales/en'>;
}
declare module 'counterpart/locales/pt-br.js' {
  declare module.exports: $Exports<'counterpart/locales/pt-br'>;
}
declare module 'counterpart/locales/ru.js' {
  declare module.exports: $Exports<'counterpart/locales/ru'>;
}
declare module 'counterpart/strftime.js' {
  declare module.exports: $Exports<'counterpart/strftime'>;
}
