// flow-typed signature: cea244404d5a88c0e756059b74e6e3bd
// flow-typed version: <<STUB>>/css_v^2.2.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css/lib/parse/index' {
  declare module.exports: any;
}

declare module 'css/lib/stringify/compiler' {
  declare module.exports: any;
}

declare module 'css/lib/stringify/compress' {
  declare module.exports: any;
}

declare module 'css/lib/stringify/identity' {
  declare module.exports: any;
}

declare module 'css/lib/stringify/index' {
  declare module.exports: any;
}

declare module 'css/lib/stringify/source-map-support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css/index' {
  declare module.exports: $Exports<'css'>;
}
declare module 'css/index.js' {
  declare module.exports: $Exports<'css'>;
}
declare module 'css/lib/parse/index.js' {
  declare module.exports: $Exports<'css/lib/parse/index'>;
}
declare module 'css/lib/stringify/compiler.js' {
  declare module.exports: $Exports<'css/lib/stringify/compiler'>;
}
declare module 'css/lib/stringify/compress.js' {
  declare module.exports: $Exports<'css/lib/stringify/compress'>;
}
declare module 'css/lib/stringify/identity.js' {
  declare module.exports: $Exports<'css/lib/stringify/identity'>;
}
declare module 'css/lib/stringify/index.js' {
  declare module.exports: $Exports<'css/lib/stringify/index'>;
}
declare module 'css/lib/stringify/source-map-support.js' {
  declare module.exports: $Exports<'css/lib/stringify/source-map-support'>;
}
