// flow-typed signature: dcbbc5bac37a137d139a82e2d2413f8d
// flow-typed version: <<STUB>>/dont-go_v^1.0.7/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dont-go'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dont-go' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dont-go/lib/dont-go' {
  declare module.exports: any;
}

declare module 'dont-go/lib/dont-go.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dont-go/lib/dont-go.js' {
  declare module.exports: $Exports<'dont-go/lib/dont-go'>;
}
declare module 'dont-go/lib/dont-go.min.js' {
  declare module.exports: $Exports<'dont-go/lib/dont-go.min'>;
}
