// flow-typed signature: 036c9c1e12133cfb4069c8f608716215
// flow-typed version: <<STUB>>/native-css_v^1.2.5/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'native-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'native-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'native-css/bin/native-css' {
  declare module.exports: any;
}

declare module 'native-css/lib/index' {
  declare module.exports: any;
}

declare module 'native-css/src/index' {
  declare module.exports: any;
}

declare module 'native-css/src/native-css' {
  declare module.exports: any;
}

declare module 'native-css/test/conversion' {
  declare module.exports: any;
}

// Filename aliases
declare module 'native-css/bin/native-css.js' {
  declare module.exports: $Exports<'native-css/bin/native-css'>;
}
declare module 'native-css/index' {
  declare module.exports: $Exports<'native-css'>;
}
declare module 'native-css/index.js' {
  declare module.exports: $Exports<'native-css'>;
}
declare module 'native-css/lib/index.js' {
  declare module.exports: $Exports<'native-css/lib/index'>;
}
declare module 'native-css/src/index.js' {
  declare module.exports: $Exports<'native-css/src/index'>;
}
declare module 'native-css/src/native-css.js' {
  declare module.exports: $Exports<'native-css/src/native-css'>;
}
declare module 'native-css/test/conversion.js' {
  declare module.exports: $Exports<'native-css/test/conversion'>;
}
