// flow-typed signature: 335dac3d7093c1d377fe801a9c108ca0
// flow-typed version: <<STUB>>/react-cookie_v^0.4.8/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cookie/dist/react-cookie' {
  declare module.exports: any;
}

declare module 'react-cookie/dist/react-cookie.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cookie/dist/react-cookie.js' {
  declare module.exports: $Exports<'react-cookie/dist/react-cookie'>;
}
declare module 'react-cookie/dist/react-cookie.min.js' {
  declare module.exports: $Exports<'react-cookie/dist/react-cookie.min'>;
}
declare module 'react-cookie/index' {
  declare module.exports: $Exports<'react-cookie'>;
}
declare module 'react-cookie/index.js' {
  declare module.exports: $Exports<'react-cookie'>;
}
