// flow-typed signature: e9adf43fa3179401b3ce8e7c079bfb27
// flow-typed version: <<STUB>>/react-cookie_v^1.0.4/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cookie/build/cookie' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cookie/build/cookie.js' {
  declare module.exports: $Exports<'react-cookie/build/cookie'>;
}
