// flow-typed signature: 79877947d896bc2a79a3c010841e7bd9
// flow-typed version: <<STUB>>/react-interpolate-component_v^0.10.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-interpolate-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-interpolate-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-interpolate-component/index' {
  declare module.exports: $Exports<'react-interpolate-component'>;
}
declare module 'react-interpolate-component/index.js' {
  declare module.exports: $Exports<'react-interpolate-component'>;
}
