// flow-typed signature: a7390b1179475f6ed63c3021e7e8517b
// flow-typed version: <<STUB>>/react-progressive-image_v^0.1.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-progressive-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-progressive-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-progressive-image/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-progressive-image/dist' {
  declare module.exports: any;
}

declare module 'react-progressive-image/umd/react-progressive-image.min' {
  declare module.exports: any;
}

declare module 'react-progressive-image/webpack.config.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-progressive-image/__tests__/index.js' {
  declare module.exports: $Exports<'react-progressive-image/__tests__/index'>;
}
declare module 'react-progressive-image/dist.js' {
  declare module.exports: $Exports<'react-progressive-image/dist'>;
}
declare module 'react-progressive-image/index' {
  declare module.exports: $Exports<'react-progressive-image'>;
}
declare module 'react-progressive-image/index.js' {
  declare module.exports: $Exports<'react-progressive-image'>;
}
declare module 'react-progressive-image/umd/react-progressive-image.min.js' {
  declare module.exports: $Exports<'react-progressive-image/umd/react-progressive-image.min'>;
}
declare module 'react-progressive-image/webpack.config.umd.js' {
  declare module.exports: $Exports<'react-progressive-image/webpack.config.umd'>;
}
