// flow-typed signature: f03c6e2b426c23662a3f04f9659fadf8
// flow-typed version: <<STUB>>/react-translate-component_v^0.13.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-translate-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-translate-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-translate-component/index' {
  declare module.exports: $Exports<'react-translate-component'>;
}
declare module 'react-translate-component/index.js' {
  declare module.exports: $Exports<'react-translate-component'>;
}
